package com.TimedSend.mapper;

import com.TimedSend.model.Tradingresult;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

/**
 * <p>
 *  Mapper 接口
 * </p>
 *
 * @author gaocheng
 * @since 2023-02-21
 */
public interface TradingresultMapper extends BaseMapper<Tradingresult> {

    @Update(value = "<script>" +
            " DELETE " +
            " FROM TRADE.TRADINGRESULT " +
            " WHERE SERIALNUM IN  (SELECT B.SERIALNUM FROM YHUSER.TC_TRADINGRESULT B " +
            "WHERE  substr(B.KNOCKTIME,1,8) ='${date}') "+
            "</script>")
    void DeleteBatchbyDate(@Param("date") String date);

    @Update(value = "<script>"+
            "INSERT INTO  TRADE.TRADINGRESULT (SERIALNUM, ACCTID, CONTRACTNUM, CURRENCYID, EXCHID, REGID, " +
            "REGNAME, OFFERREGID, STKID, STKNAME, KNOCKQTY, POSTQTY, KNOCKPRICE, KNOCKAMT, KNOCKTIME, " +
            "KNOCKCODE, ORDERTYPE, EXCHERRORCODE, STKTYPE, TRADETYPE, DESKID, ORDEREXISTFLAG, ORDERQTY," +
            " ORDERPRICE, ORDERTIME, OPTMODE, OPTID, OPTLEVEL, BRANCHID, CUSTTYPE, BROKERID, CUSTID, " +
            "RECKONINGAMT, TRADINGRESULTTYPE, OCCURTIME, INTERNALBIZMARK, CREDITSTOCKFLAG, MEMO, " +
            "INTERNALORDERTYPE, POSTPROCESSFLAG, PRODUCTGRP, KNOCKNUM, STAMPTAX, COMMISION, " +
            "TRADETRANSFEE, RECKONINGFEE, TRANSRULEFEE, HANDLINGFEE, STKMNGFEE, EXCHTRANSFEE, " +
            "VENTUREFEE, BATCHNUM, SUBCLIENTID, OPERATIONMAC, BASKETID, FULLKNOCKAMT, ACCUREDINTEREST, " +
            "TARGETDESKID, TARGETREGID, ORDERSOURCE, EXTERIORACCTID, KNOCKBATCHNUM, UPDATEFLAG, " +
            "CLIENTID, OCCURTIME2, RETURNTIME2, TRADECURRENCYID, EXCHRATE, INSTRUCTID, LIMITTYPE, " +
            "QTY2, PRICE2, REPURCHASEDAY, BUSINESSMARK, RETURNTIME1, MS_RECEIVE, MS_RETURN, " +
            "MULTINSTANCEID, STKID2, ETL_DATE) " +
            "SELECT SERIALNUM, ACCTID, CONTRACTNUM, CURRENCYID, EXCHID, REGID, " +
            "REGNAME, OFFERREGID, STKID, STKNAME, KNOCKQTY, POSTQTY, KNOCKPRICE, KNOCKAMT, KNOCKTIME, " +
            "KNOCKCODE, ORDERTYPE, EXCHERRORCODE, STKTYPE, TRADETYPE, DESKID, ORDEREXISTFLAG, ORDERQTY, " +
            "ORDERPRICE, ORDERTIME, OPTMODE, OPTID, OPTLEVEL, BRANCHID, CUSTTYPE, BROKERID, CUSTID," +
            " RECKONINGAMT, TRADINGRESULTTYPE, OCCURTIME, INTERNALBIZMARK, CREDITSTOCKFLAG, MEMO, " +
            "INTERNALORDERTYPE, POSTPROCESSFLAG, PRODUCTGRP, KNOCKNUM, STAMPTAX, COMMISION, " +
            "TRADETRANSFEE, RECKONINGFEE, TRANSRULEFEE, HANDLINGFEE, STKMNGFEE, EXCHTRANSFEE," +
            " VENTUREFEE, BATCHNUM, SUBCLIENTID, OPERATIONMAC, BASKETID, FULLKNOCKAMT, ACCUREDINTEREST, " +
            "TARGETDESKID, TARGETREGID, ORDERSOURCE, EXTERIORACCTID, KNOCKBATCHNUM, UPDATEFLAG, " +
            "CLIENTID, OCCURTIME2, RETURNTIME2, TRADECURRENCYID, EXCHRATE, INSTRUCTID, LIMITTYPE, " +
            "QTY2, PRICE2, REPURCHASEDAY, BUSINESSMARK, RETURNTIME1, MS_RECEIVE, MS_RETURN, " +
            "MULTINSTANCEID, STKID2, ETL_DATE " +
            "FROM YHUSER.TC_TRADINGRESULT "+
            "WHERE TC_ID = '${taskID}' AND substr(KNOCKTIME,1,8) ='${date}' " +
            "ORDER BY  KNOCKTIME ASC"+
            "</script>"
    )
    void insertBatch(@Param("taskID") String taskID, @Param("date") String date);


}
